name: 'Cargo JUnit Transformer'
description: 'Transform cargo test output to junit format'
author: 'King.Li'
inputs: 
  inputFile:
    description: 'File containing cargo test output'
    required: true
  outputFile:
    description: 'File containing junit output'
    default: 'junit.xml'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.inputFile }}
    - ${{ inputs.outputFile }}